theme: jekyll-theme-architect
title: Yaksa
description: High-performance Noncontiguous Data Management
show_downloads: true

github:
  repository_url: https://github.com/pmodels/yaksa
  repository_name: yaksa
  is_project_page: true
  download_url: https://github.com/pmodels/yaksa/releases
  support_url: https://forum.yaksa.org
  documentation_url: https://github.com/pmodels/yaksa/wiki
  owner_url: https://github.com/orgs/pmodels/people
  license_url: githubusercontent.com/pmodels/yaksa/master/COPYRIGHT
  cla_url: https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement
